[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F -R
autostart=true
autorestart=true
startretries=5
startsecs=1
stderr_logfile=/var/log/php-fpm.err.log
stdout_logfile=/var/log/php-fpm.out.log

[program:nginx]
command=nginx -g "daemon off; error_log /var/log/nginx/error.log warn;"
autostart=true
autorestart=true
startretries=5
startsecs=5
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log
